### ISSUE TITLE
label precision maybe so bad

### ISSUE THREAD

**Issue by hylrh2008** [pterhoer/MAAD-Face#1]
in Annotated Sample Images section,i found the first row this man's Wearing Necktie is 1,but i can't find any tie in this pic.

**Comment by pterhoer** [comment]
Hi hylrh2008,

thank you for your comment.

The man in the picture wears a scarf that runs down the front and thus takes on the shape of a necktie.
This might be reason for the annotation: Wearing Necktie is 1.

Please note that the provided annotations are not perfectly correct. 
In case of "Wearing Necktie" in MAAD-Face, the accuracy is 0.91, the precision is 0.84, and the recall is 0.98.
For LFW, "Wearing Necktie" achieved an accuracy of 0.76, a precision of 0.66, and a recall of 0.83 in our label-correctness evaluation.
For CelebA, "Wearing Necktie" reached an accuracy of 0.85, a precision of 0.72, and a recall of 0.97.

Even if MAAD-Face provides annotations of higher quality, please take into account that this are not error-free.

Best regards
Philipp
