### ISSUE TITLE
explicit consent of data subjects

### ISSUE THREAD

**Issue by jobohrerBerlin** [pterhoer/MAAD-Face#3]
Hi all, that is an interesting data set. Can you tell if the data subjects gave their explicit consent? That may influence whether we use your data.

**Comment by pterhoer** [comment]
Hi jobohrerBerlin,

thank you for your interest in this data project. 

The images were collected by the Visual Geometry Group at the University of Oxford and known as VGGFace2. This dataset is available for further distribution and research purposes under the same terms of the Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license. We only make us of these images to produce annotations. Consequently, I can't answer your question, but you might ask the authors of the VGGFace2 paper.

I hope this answer helps you.

Best regards
Philipp

**Comment by adamhrv** [comment]
The dataset was created by scraping images from  google, many of which are copyrighted. How is it even remotely possible that the subjects provided consent for use in face recognition research projects?
https://web.archive.org/web/20200530132756/http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/

**Comment by adamhrv** [comment]
Philipp is incorrectly referring to the list of URLs as the "dataset", and erroneously applying the license of the "dataset-list" of URLs as CC. VGG does not provide any licensing information for the images nor can override the image licenses with their Creative Commons license. Oxford's VGG has stopped distributing the dataset and the models, citing an issue from the University's legal team.
