### ISSUE TITLE
LFW Attributes after thresholding

### ISSUE THREAD

**Issue by MukundVarmaT** [pterhoer/MAAD-Face#6]
Hi, 

Would it be possible to share the attributes for each image from the LFW dataset after thresholding or perhaps the thresholds themselves? 

Thanks and Regards.

**Comment by pterhoer** [comment]
Hi MukundVarmaT,

you can find the attributes (upper and lower) thresholds below.

Good luck with your research
Philipp


lfw_thresholds = {
        'Male' : [-0.5, 1.0],
        'Asian' : [-0.6, 0.7],
        'White' : [-1.0, 1.0],
        'Black' : [-0.6, 0.6],
        'Baby' : [-0.1, 0.1],
        'Child' : [-0.1, 0.1],
        'Youth' : [-0.1, 0.1],
        'Middle_Aged' : [-0.6, 0.3],
        'Senior' : [-1.0, 0.8],
        'Black_Hair' : [-1.0, 0.7],
        'Blond_Hair' : [-0.7, 0.2],
        'Brown_Hair' : [-1.0, 1.2],
        'Bald' : [-1.0, 0.8],
        'No_Eyewear' : [-1.0, 0.6],
        'Eyeglasses' : [-0.5, 0.5],
        'Sunglasses' : [-0.6, 0.3],
        'Mustache' : [-0.6, 0.9],
        'Smiling' : [-0.7, 1.0],
        'Frowning' : [-1.6, 1.2],
        'Chubby' : [-1.1, 1.3],
        'Blurry' : [-1.3, 0.5],
        'Harsh_Lighting' : [-1.3, 2.3],
        'Flash' : [-1.2, 0.8],
        'Soft_Lighting' : [-0.9, 1.65],
        'Outdoor' : [-1.3, 1.3],
        'Curly_Hair' : [-0.1, 0.1],
        'Wavy_Hair' : [-1.2, 1.1],
        'Straight_Hair' : [-0.1, 0.1],
        'Receding_Hairline' : [-0.1, 0.1],
        'Bangs' : [-0.7, 1.2],
        'Sideburns' : [-0.9, 0.4],
        'Fully_Visible_Forehead' : [-1.4, 0.6],
        'Partially_Visible_Forehead' : [-1.0, 0.5],
        'Obstructed_Forehead' : [-0.7, 0.7],
        'Bushy_Eyebrows' : [-0.9, 1.1],
        'Arched_Eyebrows' : [-1.4, 1.1],
        'Narrow_Eyes' : [-1.1, 0.9],
        'Eyes_Open' : [-0.8, 0.9],
        'Big_Nose' : [-0.5, 0.9],
        'Pointy_Nose' : [-0.9, 0.9],
        'Big_Lips' : [-1.1, 1.2],
        'Mouth_Closed' : [-1.0, 1.1],
        'Mouth_Slightly_Open' : [-1.6, 0.9],
        'Mouth_Wide_Open' : [-0.5, 0.9],
        'Teeth_Not_Visible' : [-0.6, 1.7],
        'No_Beard' : [-1.2, 1.2],
        'Goatee' : [-0.5, 1.3],
        'Round_Jaw' : [-0.1, 0.1],
        'Double_Chin' : [-1.2, 0.9],
        'Wearing_Hat' : [-0.6, 1.0],
        'Oval_Face' : [-0.9, 1.4],
        'Square_Face' : [-1.0, 0.1],
        'Round_Face' : [-1.1, 0.9],
        'Color_Photo' : [-2.7, 0.0],
        'Posed_Photo' : [-0.9, 1.5],
        'Attractive_Man' : [-0.1, 0.1],
        'Attractive_Woman' : [-0.5, 0.9],
        'Indian' : [-0.1, 0.1],
        'Gray_Hair' : [-0.9, 0.5],
        'Bags_Under_Eyes' : [-0.8, 0.9],
        'Heavy_Makeup' : [-0.5, 0.8],
        'Rosy_Cheeks' : [-1.0, 0.9],
        'Shiny_Skin' : [-1.2, 0.5],
        'Pale_Skin' : [-1.2, 1.1],
        "5_o_Clock_Shadow" : [-1.2, 1.3],
        'Strong_Nose-Mouth_Lines' : [-1.0, 0.7],
        'Wearing_Lipstick' : [-1.0, 1.0],
        'Flushed_Face' : [-1.2, 1.0],
        'High_Cheekbones' : [-1.0, 0.8],
        'Brown_Eyes' : [-1.3, 1.1],
        'Wearing_Earrings' : [-0.1, 0.1],
        'Wearing_Necktie' : [-0.0, 1.0],
        'Wearing_Necklace' : [-0.1, 0.1]
    }
