### ISSUE TITLE
Massive Attribute Classifiers?

### ISSUE THREAD

**Issue by federicoromeo** [pterhoer/MAAD-Face#7]
I was wondering if you can provide the MAC model/weights to make predictions over unseen images on the 47 attributes.
That'd be very helpful, thanks.

**Comment by pterhoer** [comment]
Hi Federico,
It was decided that the model will not be made publicly available to prevent misuse/function creep of this model.
Therefore, we can not share the model. However, if it is just for a smaller number of images, we could make the predictions for you. We can discuss this via e-mail.
Best
Philipp
